server:
    port: ${SERVER_PORT}

spring:
    datasource:
        url: jdbc:postgresql://${DB_URL}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa: 
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: ${JPA_SHOW_SQL}
        hibernate: 
            ddl-auto: ${JPA_DDL_AUTO}

#Open api swagger ui 
springdoc: 
    api-docs: 
        path: /api-docs

#prefix endpoints configuration
api:
    prefix: ${API_PREFIX} 


logging:
  level:
    root: ${LOG_LEVEL}
    
  file:
    name: logs/template_app.log
    path: logs